version: "3"

services:
  web:
    image: nginx:mainline-alpine
    container_name: elastic-test-web
    ports:
      - "8080:80"
    volumes:
      - ./app:/app
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - ./logs/nginx-error.log:/var/log/nginx/error.log
      - ./logs/nginx-access.log:/var/log/ngnix/access.log
    links:
      - php

  php:
    image: php:fpm-alpine
    container_name: elastic-test-php
    volumes:
      - ./app:/app

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.3.0
    container_name: elastic-test-elasticsearch
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "xpack.security.enabled=false"
    ports:
      - "9200:9200"
    volumes:
      - ./data/elastic:/usr/share/elasticsearch/data
